name: Satis Build On Push

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: PHP Version
        run: php --version

      - name: Validate Composer Files
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer vendor directory
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-dev

      - name: Checkout GitHub pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./dist

      - name: Run Build
        run: composer run build

      - name: Commit Web Files
        run: >
          cd ./dist &&
          git fetch --prune --unshallow &&
          git config --local user.name "Micah Wood" &&
          git config --local user.email "micah@wpscholar.com" &&
          git add -A &&
          git commit -m "Satis build for commit ${{ github.sha }}" &&
          git status &&
          cd -

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          directory: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
